name: Generate Snake

on:
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v4

      # Generate snake SVG
      - uses: Platane/snk@v3
        with:
          github_user_name: Nishtha-Priya
          outputs: |
            github-snake-dark.svg?palette=github-dark

      # Push the generated SVG into 'output' branch root
      - name: Push files to output
        uses: actions-ecosystem/action-create-commit@v3
        with:
          branch: output
          commit_message: "Update snake"
          file_pattern: github-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
